using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

public class PingPong : MonoBehaviour
{
    [SerializeField] float length = 5f;
    [SerializeField] float amplitude = 5f; // U•
    [SerializeField] float period = 2f; // ˆê‰•œ‚·‚éüŠúi•bj
    [SerializeField] float phase = 0.25f; // ˆÊ‘Ši‚P‚Å‚Pü•ªj

    enum Axis { X, Y, Z };
    [SerializeField] Axis axis = Axis.Y;

    void Update()
    {
        Vector3 pos = transform.position;

        // ˆê’è‘¬“x‚Å 0 ~ length ‚ğ‰•œ‚·‚é
        // pos.y = Mathf.PingPong(Time.time, length);

        // U•AüŠúAˆÊ‘Š‚Ìİ’è
        switch (axis)
        {
            case Axis.X:
                pos.x = Mathf.PingPong(4 * amplitude * (Time.time / period + phase + 0.25f), 2 * amplitude) - amplitude;
                break;

            case Axis.Y:
                pos.y = Mathf.PingPong(4 * amplitude * (Time.time / period + phase + 0.25f), 2 * amplitude) - amplitude;
                break;

            case Axis.Z:
                pos.z = Mathf.PingPong(4 * amplitude * (Time.time / period + phase + 0.25f), 2 * amplitude) - amplitude;
                break;

            default:
                Debug.Log("axis‚ªİ’è‚³‚ê‚Ä‚¢‚Ü‚¹‚ñ");
                break;
        }

        transform.position = pos;
    }
}
